spring:
  profiles:
    active:
      - test
    group:
      test:
        - key-test
        - db-test
      prod:
        - key-prod
        - db-prod
    include:
      - db
      - key
      - oauth
      - jwt
      - swagger
#spring:
#  profiles:
#    include:
#      - KEY
#      - JWT
#      - OAUTH
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://j8d108.p.ssafy.io/Favoreat?serverTimezone=Asia/Seoul
#    username: ssafy
#    password: ${mysql-test-password}
#  jpa:
#    properties:
#      hibernate:
#        show-sql: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#jwt:
#  secretKey: ${jwt-secret}
#jwt:
#  access:
#    expiration: 3600000 # 1시간
#    header: Authorization
#
#  refresh:
#    expiration: 1209600000 # 2주
#    header: Authorization-refresh

#springdoc:
#  version: "v1"
#  packages-to-scan: com.example.backend.api.controller
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#  api-docs:
#    groups:
#      enabled: true
#    path: "/api-docs"
#  cache:
#    disabled: true
