kakao-client-id: 3f660847d40155171d5d2300672e2f73
kakao-client-secret: w50qQUwy9BMIeHyPMQ3WSORVTYivZU4S
jwt-secret : dhsmfanjajrwl

--- # test 설정
spring:
  config:
    activate:
      on-profile: "key-test"

mysql-test-username : ssafy
mysql-test-password : ssafy

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "key-prod"

mysql-prod-username : ssafy
mysql-prod-password : ssafy