spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8d108.p.ssafy.io/Favoreat?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3f660847d40155171d5d2300672e2f73 # 보안 수정할 것
            client-secret: w50qQUwy9BMIeHyPMQ3WSORVTYivZU4S
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org:
      hibernate:
        SQL: debug
jwt:
  secretKey: dhsmfanjajrwl

  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

springdoc:
  version: "v1"
  packages-to-scan: com.example.backend.api.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    groups:
      enabled: true
    path: "/api-docs"
  cache:
    disabled: true